In [38]:
import pandas as pd
import numpy as np

In [39]:
df = pd.read_csv('C:/Users/User/OneDrive/Desktop/PROJECT ML/Data/obesity_level2.csv')

In [40]:
df.sample(5)

,id,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,0be1dad
6272,6272,Female,26.000000,1.556211,110.640929,1,1,3.000000,3.000000,Sometimes,0,1.495830,0,0.000000,0.466169,Sometimes,Public_Transportation,Obesity_Type_III
3766,3766,Female,40.993179,1.567973,81.022119,1,1,2.921576,3.000000,Sometimes,0,1.005727,0,1.034031,0.000000,0,Automobile,Obesity_Type_I
12662,12662,Male,20.000000,1.740000,75.000000,1,1,3.000000,3.000000,Frequently,0,2.000000,0,1.000000,1.000000,0,Automobile,0rmal_Weight
15485,15485,Male,26.945139,1.644053,116.893105,1,1,1.588185,3.000000,Sometimes,0,1.000000,0,0.425621,0.631422,Sometimes,Public_Transportation,Obesity_Type_II
14458,14458,Male,22.719385,1.867410,121.684311,1,1,2.654076,2.806298,Sometimes,0,1.970508,0,0.736032,0.000000,Sometimes,Public_Transportation,Obesity_Type_II

In [41]:
df.describe()

,id,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE
count,20758.00000,20745.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000
mean,10378.50000,23.840654,1.700245,87.887768,0.819636,0.914443,2.445908,2.761332,0.011803,2.029418,0.033096,0.981747,0.616756
std,5992.46278,5.687531,0.087312,26.379443,0.384500,0.279716,0.533218,0.705375,0.108000,0.608467,0.178891,0.838302,0.602113
min,0.00000,14.000000,1.450000,39.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,5189.25000,20.000000,1.631856,66.000000,1.000000,1.000000,2.000000,3.000000,0.000000,1.792022,0.000000,0.008013,0.000000
50%,10378.50000,22.815416,1.700000,84.064875,1.000000,1.000000,2.393837,3.000000,0.000000,2.000000,0.000000,1.000000,0.573887
75%,15567.75000,26.000000,1.762887,111.600553,1.000000,1.000000,3.000000,3.000000,0.000000,2.549617,0.000000,1.587406,1.000000
max,20757.00000,61.000000,1.975663,165.057269,1.000000,1.000000,3.000000,4.000000,1.000000,3.000000,1.000000,3.000000,2.000000

In [42]:
df.rename(columns={
    'FAVC': 'Freq_consump_of_high-caloric_food',
    'FCVC': 'Freq_of_veg_consump',
    'CAEC': 'Consump_of_food_btw_meals',
    'NCP': 'No._of_main_meals',
    'CH2O': 'Daily_water_intake(L)',
    'FAF': 'Phy_activity_freq',
    'TUE': 'Time_using_tech_devices',
    'CALC': 'Alcohol_consumption',
    'MTRANS': 'Transportation_used',
    '0be1dad': 'Obesity_Level'
}, inplace=True)

In [43]:
df

,id,Gender,Age,Height,Weight,family_history_with_overweight,Freq_consump_of_high-caloric_food,Freq_of_veg_consump,No._of_main_meals,Consump_of_food_btw_meals,SMOKE,Daily_water_intake(L),SCC,Phy_activity_freq,Time_using_tech_devices,Alcohol_consumption,Transportation_used,Obesity_Level
0,0,Male,24.443011,1.699998,81.669950,1,1,2.000000,2.983297,Sometimes,0,2.763573,0,0.000000,0.976473,Sometimes,Public_Transportation,Overweight_Level_II
1,1,Female,18.000000,1.560000,57.000000,1,1,2.000000,3.000000,Frequently,0,2.000000,0,1.000000,1.000000,0,Automobile,0rmal_Weight
2,2,Female,18.000000,1.711460,50.165754,1,1,1.880534,1.411685,Sometimes,0,1.910378,0,0.866045,1.673584,0,Public_Transportation,Insufficient_Weight
3,3,Female,NaN,1.710730,131.274851,1,1,3.000000,3.000000,Sometimes,0,1.674061,0,1.467863,0.780199,Sometimes,Public_Transportation,Obesity_Type_III
4,4,Male,31.641081,1.914186,93.798055,1,1,2.679664,1.971472,Sometimes,0,1.979848,0,1.967973,0.931721,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20753,20753,Male,25.137087,1.766626,114.187096,1,1,2.919584,3.000000,Sometimes,0,2.151809,0,1.330519,0.196680,Sometimes,Public_Transportation,Obesity_Type_II
20754,20754,Male,18.000000,1.710000,50.000000,0,1,3.000000,4.000000,Frequently,0,1.000000,0,2.000000,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
20755,20755,Male,20.101026,1.819557,105.580491,1,1,2.407817,3.000000,Sometimes,0,2.000000,0,1.158040,1.198439,0,Public_Transportation,Obesity_Type_II
20756,20756,Male,NaN,1.700000,83.520113,1,1,2.671238,1.971472,Sometimes,0,2.144838,0,0.000000,0.973834,0,Automobile,Overweight_Level_II
20757,20757,Male,26.680376,1.816547,118.134898,1,1,3.000000,3.000000,Sometimes,0,2.003563,0,0.684487,0.713823,Sometimes,Public_Transportation,Obesity_Type_II

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   id                                 20758 non-null  int64
 1   Gender                             20758 non-null  object
 2   Age                                20745 non-null  float64
 3   Height                             20758 non-null  float64
 4   Weight                             20758 non-null  float64
 5   family_history_with_overweight     20758 non-null  int64
 6   Freq_consump_of_high-caloric_food  20758 non-null  int64
 7   Freq_of_veg_consump                20758 non-null  float64
 8   No._of_main_meals                  20758 non-null  float64
 9   Consump_of_food_btw_meals          20758 non-null  object
 10  SMOKE                              20758 non-null  int64
 11  Daily_water_intake(L)              20758 non-null  float64
 12  SCC                                20758 non-null  int64
 13  Phy_activity_freq                  20758 non-null  float64
 14  Time_using_tech_devices            20758 non-null  float64
 15  Alcohol_consumption                20758 non-null  object
 16  Transportation_used                20758 non-null  object
 17  Obesity_Level                      20758 non-null  object
dtypes: float64(8), int64(5), object(5)
memory usage: 2.9+ MB

In [45]:
print(df.isnull().sum())

id                                    0
Gender                                0
Age                                  13
Height                                0
Weight                                0
family_history_with_overweight        0
Freq_consump_of_high-caloric_food     0
Freq_of_veg_consump                   0
No._of_main_meals                     0
Consump_of_food_btw_meals             0
SMOKE                                 0
Daily_water_intake(L)                 0
SCC                                   0
Phy_activity_freq                     0
Time_using_tech_devices               0
Alcohol_consumption                   0
Transportation_used                   0
Obesity_Level                         0
dtype: int64

In [46]:
# X = df.drop(columns=['id','Obesity_Level','SCC'])
# Y = df['Obesity_Level']

In [47]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [48]:
# X_train.iloc[:,14]

In [49]:
print(df.dtypes)

id                                     int64
Gender                                object
Age                                  float64
Height                               float64
Weight                               float64
family_history_with_overweight         int64
Freq_consump_of_high-caloric_food      int64
Freq_of_veg_consump                  float64
No._of_main_meals                    float64
Consump_of_food_btw_meals             object
SMOKE                                  int64
Daily_water_intake(L)                float64
SCC                                    int64
Phy_activity_freq                    float64
Time_using_tech_devices              float64
Alcohol_consumption                   object
Transportation_used                   object
Obesity_Level                         object
dtype: object

In [50]:
# df['Age'] = df['Age'].astype(int)
df['Age'].mean()

23.840654485707397

In [51]:
# print(X_train.isnull().sum())

In [52]:
df['Alcohol_consumption'].value_counts()

Alcohol_consumption
Sometimes     15066
0              5163
Frequently      529
Name: count, dtype: int64

In [53]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [54]:
imputer = SimpleImputer(strategy='mean')
imputed_age = imputer.fit_transform(df[['Age']])

In [55]:
df['Age'] = imputed_age
df['Age'] = df['Age'].astype(int)

In [56]:
df['Age'].isnull().sum()

0

In [57]:
df.isnull().sum()

id                                   0
Gender                               0
Age                                  0
Height                               0
Weight                               0
family_history_with_overweight       0
Freq_consump_of_high-caloric_food    0
Freq_of_veg_consump                  0
No._of_main_meals                    0
Consump_of_food_btw_meals            0
SMOKE                                0
Daily_water_intake(L)                0
SCC                                  0
Phy_activity_freq                    0
Time_using_tech_devices              0
Alcohol_consumption                  0
Transportation_used                  0
Obesity_Level                        0
dtype: int64

In [58]:
X = df.drop(columns=['id','Obesity_Level','SCC'])
Y = df['Obesity_Level']

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [60]:
print(X_train.isnull().sum())

Gender                               0
Age                                  0
Height                               0
Weight                               0
family_history_with_overweight       0
Freq_consump_of_high-caloric_food    0
Freq_of_veg_consump                  0
No._of_main_meals                    0
Consump_of_food_btw_meals            0
SMOKE                                0
Daily_water_intake(L)                0
Phy_activity_freq                    0
Time_using_tech_devices              0
Alcohol_consumption                  0
Transportation_used                  0
dtype: int64

In [61]:
print(X_train.isnull().sum())

Gender                               0
Age                                  0
Height                               0
Weight                               0
family_history_with_overweight       0
Freq_consump_of_high-caloric_food    0
Freq_of_veg_consump                  0
No._of_main_meals                    0
Consump_of_food_btw_meals            0
SMOKE                                0
Daily_water_intake(L)                0
Phy_activity_freq                    0
Time_using_tech_devices              0
Alcohol_consumption                  0
Transportation_used                  0
dtype: int64

In [62]:
# Define the column names
categorical_cols = ['Gender', 'Transportation_used']
ordinal_cols = ['Consump_of_food_btw_meals', 'Alcohol_consumption']
numerical_cols = ['Age', 'Height', 'Weight']

In [63]:
preprocessor = ColumnTransformer(
    transformers=[
        # ('impute_age', SimpleImputer(strategy='mean'), ['Age']),  # Impute missing values in Age
        ('ohe', OneHotEncoder(sparse=False, handle_unknown='ignore'), categorical_cols),  # One-hot encoding categorical columns
        ('oe', ColumnTransformer(
            transformers=[
                ('food', OrdinalEncoder(categories=[['0', 'Sometimes', 'Frequently', 'Always']], handle_unknown='use_encoded_value', unknown_value=-1), ['Consump_of_food_btw_meals']),
                ('alcohol', OrdinalEncoder(categories=[['0', 'Sometimes', 'Frequently']], handle_unknown='use_encoded_value', unknown_value=-1), ['Alcohol_consumption'])
            ],
            remainder='passthrough'
        ), ordinal_cols),  # Ordinal encoding
        ('scale', StandardScaler(), numerical_cols)  # Scaling numerical columns
    ],
    remainder='passthrough'
)

In [70]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier


pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', RandomForestClassifier())
])

C:\Users\User\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [71]:
pipe.fit(X_train,y_train)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse=False),
                                                  ['Gender',
                                                   'Transportation_used']),
                                                 ('oe',
                                                  ColumnTransformer(remainder='passthrough',
                                                                    transformers=[('food',
                                                                                   OrdinalEncoder(categories=[['0',
                                                                                                               'Sometimes',
                                                                                                               'Frequently',
                                                                                                               'Always']],
                                                                                                  handle_unknown='use_encoded_value',
                                                                                                  unknown_value=-1),
                                                                                   ['Consump_of_food_btw_meals']),
                                                                                  ('alcohol',
                                                                                   OrdinalEncoder(categories=[['0',
                                                                                                               'Sometimes',
                                                                                                               'Frequently']],
                                                                                                  handle_unknown='use_encoded_value',
                                                                                                  unknown_value=-1),
                                                                                   ['Alcohol_consumption'])]),
                                                  ['Consump_of_food_btw_meals',
                                                   'Alcohol_consumption']),
                                                 ('scale', StandardScaler(),
                                                  ['Age', 'Height',
                                                   'Weight'])])),
                ('model', RandomForestClassifier())])

In [72]:
X_train_transformed

array([[0.      , 1.      , 1.      , ..., 2.      , 3.      , 1.      ],
       [0.      , 1.      , 0.      , ..., 2.      , 2.      , 1.      ],
       [0.      , 1.      , 0.      , ..., 1.645338, 0.739881, 0.      ],
       ...,
       [0.      , 1.      , 0.      , ..., 3.      , 2.      , 0.      ],
       [1.      , 0.      , 0.      , ..., 2.770732, 0.      , 0.237307],
       [0.      , 1.      , 1.      , ..., 2.745242, 2.545707, 0.      ]])

In [37]:
transformer.get_feature_names_out(input_features=X_train.columns)

NameError: name 'transformer' is not defined

In [42]:
X_train_transformed = pd.DataFrame(X_train_transformed,columns=transformer.get_feature_names_out(input_features=X_train.columns))

In [43]:
X_train_transformed

,tnf1__Gender_Female,tnf1__Gender_Male,tnf1__Transportation_used_Automobile,tnf1__Transportation_used_Bike,tnf1__Transportation_used_Motorbike,tnf1__Transportation_used_Public_Transportation,tnf1__Transportation_used_Walking,tnf2__Age,tnf2__Weight,tnf3__Consump_of_food_btw_meals,tnf4__Alcohol_consumption
0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,-1.199393,0.343527,3.0,0.0
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,-0.213125,-1.256602,1.0,0.0
2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,-0.357434,1.294154,1.0,1.0
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.977056,-0.302254,1.0,1.0
4,0.0,1.0,0.0,0.0,0.0,1.0,0.0,-0.155281,0.267553,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
16601,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.025374,-0.285435,1.0,0.0
16602,0.0,1.0,0.0,0.0,0.0,1.0,0.0,-0.329300,0.267553,1.0,1.0
16603,0.0,1.0,0.0,0.0,0.0,1.0,0.0,-0.503318,-0.758100,3.0,1.0
16604,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.366775,0.911043,1.0,1.0
16605,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.454637,0.761341,1.0,1.0