In [39]:
import pandas as pd

In [40]:
df = pd.read_csv('C:/Users/User/OneDrive/Desktop/PROJECT ML/Data/obesity_level2.csv')

In [41]:
df.sample(5)

,id,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,0be1dad
7076,7076,Female,21.000000,1.550000,63.000000,1,1,2.000000,1.000000,Sometimes,0,2.000000,0,1.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_I
4977,4977,Female,19.880360,1.680858,49.742931,0,0,2.886260,3.559841,Frequently,0,1.636326,0,2.000000,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
18877,18877,Female,26.000000,1.641918,111.830924,1,1,3.000000,3.000000,Sometimes,0,2.635454,0,0.000000,0.171034,Sometimes,Public_Transportation,Obesity_Type_III
17411,17411,Female,20.975973,1.710948,50.000000,1,1,2.918113,3.000000,Frequently,0,2.000000,0,0.891444,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
13086,13086,Female,19.376997,1.600264,45.000000,0,0,3.000000,3.000000,Frequently,0,2.326635,0,1.727114,0.000000,0,Public_Transportation,Insufficient_Weight

In [42]:
df.describe()

,id,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE
count,20758.00000,20745.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000
mean,10378.50000,23.840654,1.700245,87.887768,0.819636,0.914443,2.445908,2.761332,0.011803,2.029418,0.033096,0.981747,0.616756
std,5992.46278,5.687531,0.087312,26.379443,0.384500,0.279716,0.533218,0.705375,0.108000,0.608467,0.178891,0.838302,0.602113
min,0.00000,14.000000,1.450000,39.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,5189.25000,20.000000,1.631856,66.000000,1.000000,1.000000,2.000000,3.000000,0.000000,1.792022,0.000000,0.008013,0.000000
50%,10378.50000,22.815416,1.700000,84.064875,1.000000,1.000000,2.393837,3.000000,0.000000,2.000000,0.000000,1.000000,0.573887
75%,15567.75000,26.000000,1.762887,111.600553,1.000000,1.000000,3.000000,3.000000,0.000000,2.549617,0.000000,1.587406,1.000000
max,20757.00000,61.000000,1.975663,165.057269,1.000000,1.000000,3.000000,4.000000,1.000000,3.000000,1.000000,3.000000,2.000000

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20758 non-null  int64
 1   Gender                          20758 non-null  object
 2   Age                             20745 non-null  float64
 3   Height                          20758 non-null  float64
 4   Weight                          20758 non-null  float64
 5   family_history_with_overweight  20758 non-null  int64
 6   FAVC                            20758 non-null  int64
 7   FCVC                            20758 non-null  float64
 8   NCP                             20758 non-null  float64
 9   CAEC                            20758 non-null  object
 10  SMOKE                           20758 non-null  int64
 11  CH2O                            20758 non-null  float64
 12  SCC                             20758 non-null  int64
 13  FAF                             20758 non-null  float64
 14  TUE                             20758 non-null  float64
 15  CALC                            20758 non-null  object
 16  MTRANS                          20758 non-null  object
 17  0be1dad                         20758 non-null  object
dtypes: float64(8), int64(5), object(5)
memory usage: 2.9+ MB

In [44]:
df.isnull().sum()

id                                 0
Gender                             0
Age                               13
Height                             0
Weight                             0
family_history_with_overweight     0
FAVC                               0
FCVC                               0
NCP                                0
CAEC                               0
SMOKE                              0
CH2O                               0
SCC                                0
FAF                                0
TUE                                0
CALC                               0
MTRANS                             0
0be1dad                            0
dtype: int64

In [45]:
df.rename(columns={
    'FAVC': 'Freq_consump_of_high-caloric_food',
    'FCVC': 'Freq_of_veg_consump',
    'CAEC': 'Consump_of_food_btw_meals',
    'NCP': 'No._of_main_meals',
    'CH2O': 'Daily_water_intake(L)',
    'FAF': 'Phy_activity_freq',
    'TUE': 'Time_using_tech_devices',
    'CALC': 'Alcohol_consumption',
    'MTRANS': 'Transportation_used',
    '0be1dad': 'Obesity_Level'
}, inplace=True)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   id                                 20758 non-null  int64
 1   Gender                             20758 non-null  object
 2   Age                                20745 non-null  float64
 3   Height                             20758 non-null  float64
 4   Weight                             20758 non-null  float64
 5   family_history_with_overweight     20758 non-null  int64
 6   Freq_consump_of_high-caloric_food  20758 non-null  int64
 7   Freq_of_veg_consump                20758 non-null  float64
 8   No._of_main_meals                  20758 non-null  float64
 9   Consump_of_food_btw_meals          20758 non-null  object
 10  SMOKE                              20758 non-null  int64
 11  Daily_water_intake(L)              20758 non-null  float64
 12  SCC                                20758 non-null  int64
 13  Phy_activity_freq                  20758 non-null  float64
 14  Time_using_tech_devices            20758 non-null  float64
 15  Alcohol_consumption                20758 non-null  object
 16  Transportation_used                20758 non-null  object
 17  Obesity_Level                      20758 non-null  object
dtypes: float64(8), int64(5), object(5)
memory usage: 2.9+ MB

In [47]:
print(df.isnull().sum())

id                                    0
Gender                                0
Age                                  13
Height                                0
Weight                                0
family_history_with_overweight        0
Freq_consump_of_high-caloric_food     0
Freq_of_veg_consump                   0
No._of_main_meals                     0
Consump_of_food_btw_meals             0
SMOKE                                 0
Daily_water_intake(L)                 0
SCC                                   0
Phy_activity_freq                     0
Time_using_tech_devices               0
Alcohol_consumption                   0
Transportation_used                   0
Obesity_Level                         0
dtype: int64

In [48]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [49]:
imputer = SimpleImputer(strategy='mean')
imputed_age = imputer.fit_transform(df[['Age']])

In [50]:
df['Age'] = imputed_age
df['Age'] = df['Age'].astype(int)

In [51]:
df.isnull().sum()

id                                   0
Gender                               0
Age                                  0
Height                               0
Weight                               0
family_history_with_overweight       0
Freq_consump_of_high-caloric_food    0
Freq_of_veg_consump                  0
No._of_main_meals                    0
Consump_of_food_btw_meals            0
SMOKE                                0
Daily_water_intake(L)                0
SCC                                  0
Phy_activity_freq                    0
Time_using_tech_devices              0
Alcohol_consumption                  0
Transportation_used                  0
Obesity_Level                        0
dtype: int64

In [52]:
X = df.drop(columns=['id','Obesity_Level','SCC'])
Y = df['Obesity_Level']

In [53]:
for x in range(20):
    print(Y[x])

Overweight_Level_II
Normal_Weight
Insufficient_Weight
Obesity_Type_III
Overweight_Level_II
Insufficient_Weight
Obesity_Type_II
Obesity_Type_II
Overweight_Level_I
Obesity_Type_III
Overweight_Level_I
Normal_Weight
Obesity_Type_I
Obesity_Type_III
Normal_Weight
Obesity_Type_II
Overweight_Level_II
Normal_Weight
Overweight_Level_II
Obesity_Type_II

In [56]:
# Label encode the target variable
label_encoder = LabelEncoder()
Y = label_encoder.fit_transform(Y)

In [57]:
for x in range(20):
    print(Y[x])

6
1
0
4
6
0
3
3
5
4
5
1
2
4
1
3
6
1
6
3

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [83]:
X_train.tail(100)

,Gender,Age,Height,Weight,family_history_with_overweight,Freq_consump_of_high-caloric_food,Freq_of_veg_consump,No._of_main_meals,Consump_of_food_btw_meals,SMOKE,Daily_water_intake(L),Phy_activity_freq,Time_using_tech_devices,Alcohol_consumption,Transportation_used
11837,Female,21,1.716691,51.149283,1,1,2.886157,3.000000,Frequently,0,1.253803,0.520407,0.256382,0,Public_Transportation
2454,Male,17,1.710800,51.437985,1,1,2.183540,3.000000,Sometimes,0,2.000000,0.000000,1.000000,Sometimes,Public_Transportation
19488,Female,21,1.500000,57.000000,1,1,2.000000,3.000000,Always,0,1.000000,0.000000,0.000000,Sometimes,Public_Transportation
15265,Male,30,1.782756,120.699119,1,1,2.341999,3.000000,Sometimes,0,2.297896,1.097905,0.735868,Sometimes,Automobile
13067,Female,20,1.734092,132.940660,1,1,3.000000,3.000000,Sometimes,0,2.833770,1.682490,0.780199,Sometimes,Public_Transportation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,Female,18,1.722461,80.442775,1,1,2.628791,2.562895,Sometimes,0,1.844645,0.288032,0.722276,0,Public_Transportation
11964,Male,22,1.750000,95.000000,1,0,3.000000,3.000000,Sometimes,0,2.000000,3.000000,0.000000,Sometimes,Public_Transportation
5390,Male,21,1.620000,68.000000,0,1,2.000000,3.000000,Always,0,3.000000,2.000000,0.000000,Sometimes,Public_Transportation
860,Female,26,1.650125,111.939671,1,1,3.000000,3.000000,Sometimes,0,2.770732,0.000000,0.237307,Sometimes,Public_Transportation
15795,Male,37,1.774330,107.998815,1,1,2.964419,2.902766,Sometimes,0,2.745242,2.545707,0.000000,Sometimes,Automobile

In [86]:
df['Transportation_used'].unique().

SyntaxError: invalid syntax (1781362701.py, line 1)

In [60]:
print(X_train.isnull().sum())

Gender                               0
Age                                  0
Height                               0
Weight                               0
family_history_with_overweight       0
Freq_consump_of_high-caloric_food    0
Freq_of_veg_consump                  0
No._of_main_meals                    0
Consump_of_food_btw_meals            0
SMOKE                                0
Daily_water_intake(L)                0
Phy_activity_freq                    0
Time_using_tech_devices              0
Alcohol_consumption                  0
Transportation_used                  0
dtype: int64

In [61]:
# Define the column names
categorical_cols = ['Gender', 'Transportation_used']
ordinal_cols = ['Consump_of_food_btw_meals', 'Alcohol_consumption']
numerical_cols = ['Age', 'Height', 'Weight']

In [87]:
# Define the complete column transformer

preprocessor = ColumnTransformer(
    transformers=[
        ('ohe', OneHotEncoder(sparse=False, handle_unknown='ignore'), categorical_cols),  # One-hot encoding categorical columns
        ('oe', ColumnTransformer(
            transformers=[
                ('food', OrdinalEncoder(categories=[['0', 'Sometimes', 'Frequently', 'Always']], handle_unknown='use_encoded_value', unknown_value=-1), ['Consump_of_food_btw_meals']),
                ('alcohol', OrdinalEncoder(categories=[['0', 'Sometimes', 'Frequently']], handle_unknown='use_encoded_value', unknown_value=-1), ['Alcohol_consumption'])
            ],
            remainder='passthrough'
        ), ordinal_cols),  # Ordinal encoding
        ('scale', StandardScaler(), numerical_cols)  # Scaling numerical columns
    ],
    remainder='passthrough'
)

In [63]:
# !pip install xgboost

In [64]:
# !pip install lightgbm

In [65]:
# !pip install catboost

In [66]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
import xgboost as xgb
import lightgbm as lgb
# import catboost as cb
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [67]:


models = {
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'Support Vector Machine': SVC(random_state=42),
    'Ada Boost': AdaBoostClassifier(algorithm='SAMME'),
    'Neural Network': MLPClassifier(max_iter=400),
    'XGBoost': xgb.XGBClassifier(random_state=42),
    'LightGBM': lgb.LGBMClassifier(random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42),
    # 'CatBoost': cb.CatBoostClassifier(random_state=42, verbose=0)
}

# Create a dictionary to store pipelines for each model
pipelines = {}

In [68]:
from sklearn.pipeline import Pipeline

In [69]:
# Create pipelines for each model


for model_name, model in models.items():
    pipelines[model_name] = Pipeline(steps=[('preprocessor', preprocessor),
                                            ('classifier', model)])

In [70]:
pipelines

{'Decision Tree': Pipeline(steps=[('preprocessor',
                  ColumnTransformer(remainder='passthrough',
                                    transformers=[('ohe',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse=False),
                                                   ['Gender',
                                                    'Transportation_used']),
                                                  ('oe',
                                                   ColumnTransformer(remainder='passthrough',
                                                                     transformers=[('food',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently',
                                                                                                                'Always']],
                                                                                                   handle_unknown='use_encoded_val...
                                                                                                   unknown_value=-1),
                                                                                    ['Consump_of_food_btw_meals']),
                                                                                   ('alcohol',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently']],
                                                                                                   handle_unknown='use_encoded_value',
                                                                                                   unknown_value=-1),
                                                                                    ['Alcohol_consumption'])]),
                                                   ['Consump_of_food_btw_meals',
                                                    'Alcohol_consumption']),
                                                  ('scale', StandardScaler(),
                                                   ['Age', 'Height',
                                                    'Weight'])])),
                 ('classifier', DecisionTreeClassifier(random_state=42))]),
 'Random Forest': Pipeline(steps=[('preprocessor',
                  ColumnTransformer(remainder='passthrough',
                                    transformers=[('ohe',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse=False),
                                                   ['Gender',
                                                    'Transportation_used']),
                                                  ('oe',
                                                   ColumnTransformer(remainder='passthrough',
                                                                     transformers=[('food',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently',
                                                                                                                'Always']],
                                                                                                   handle_unknown='use_encoded_val...
                                                                                                   unknown_value=-1),
                                                                                    ['Consump_of_food_btw_meals']),
                                                                                   ('alcohol',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently']],
                                                                                                   handle_unknown='use_encoded_value',
                                                                                                   unknown_value=-1),
                                                                                    ['Alcohol_consumption'])]),
                                                   ['Consump_of_food_btw_meals',
                                                    'Alcohol_consumption']),
                                                  ('scale', StandardScaler(),
                                                   ['Age', 'Height',
                                                    'Weight'])])),
                 ('classifier', RandomForestClassifier(random_state=42))]),
 'Support Vector Machine': Pipeline(steps=[('preprocessor',
                  ColumnTransformer(remainder='passthrough',
                                    transformers=[('ohe',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse=False),
                                                   ['Gender',
                                                    'Transportation_used']),
                                                  ('oe',
                                                   ColumnTransformer(remainder='passthrough',
                                                                     transformers=[('food',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently',
                                                                                                                'Always']],
                                                                                                   handle_unknown='use_encoded_value',
                                                                                                   unknown_value=-1),
                                                                                    ['Consump_of_food_btw_meals']),
                                                                                   ('alcohol',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently']],
                                                                                                   handle_unknown='use_encoded_value',
                                                                                                   unknown_value=-1),
                                                                                    ['Alcohol_consumption'])]),
                                                   ['Consump_of_food_btw_meals',
                                                    'Alcohol_consumption']),
                                                  ('scale', StandardScaler(),
                                                   ['Age', 'Height',
                                                    'Weight'])])),
                 ('classifier', SVC(random_state=42))]),
 'Ada Boost': Pipeline(steps=[('preprocessor',
                  ColumnTransformer(remainder='passthrough',
                                    transformers=[('ohe',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse=False),
                                                   ['Gender',
                                                    'Transportation_used']),
                                                  ('oe',
                                                   ColumnTransformer(remainder='passthrough',
                                                                     transformers=[('food',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently',
                                                                                                                'Always']],
                                                                                                   handle_unknown='use_encoded_val...
                                                                                                   unknown_value=-1),
                                                                                    ['Consump_of_food_btw_meals']),
                                                                                   ('alcohol',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently']],
                                                                                                   handle_unknown='use_encoded_value',
                                                                                                   unknown_value=-1),
                                                                                    ['Alcohol_consumption'])]),
                                                   ['Consump_of_food_btw_meals',
                                                    'Alcohol_consumption']),
                                                  ('scale', StandardScaler(),
                                                   ['Age', 'Height',
                                                    'Weight'])])),
                 ('classifier', AdaBoostClassifier(algorithm='SAMME'))]),
 'Neural Network': Pipeline(steps=[('preprocessor',
                  ColumnTransformer(remainder='passthrough',
                                    transformers=[('ohe',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse=False),
                                                   ['Gender',
                                                    'Transportation_used']),
                                                  ('oe',
                                                   ColumnTransformer(remainder='passthrough',
                                                                     transformers=[('food',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently',
                                                                                                                'Always']],
                                                                                                   handle_unknown='use_encoded_val...
                                                                                                   unknown_value=-1),
                                                                                    ['Consump_of_food_btw_meals']),
                                                                                   ('alcohol',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently']],
                                                                                                   handle_unknown='use_encoded_value',
                                                                                                   unknown_value=-1),
                                                                                    ['Alcohol_consumption'])]),
                                                   ['Consump_of_food_btw_meals',
                                                    'Alcohol_consumption']),
                                                  ('scale', StandardScaler(),
                                                   ['Age', 'Height',
                                                    'Weight'])])),
                 ('classifier', MLPClassifier(max_iter=400))]),
 'XGBoost': Pipeline(steps=[('preprocessor',
                  ColumnTransformer(remainder='passthrough',
                                    transformers=[('ohe',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse=False),
                                                   ['Gender',
                                                    'Transportation_used']),
                                                  ('oe',
                                                   ColumnTransformer(remainder='passthrough',
                                                                     transformers=[('food',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently',
                                                                                                                'Always']],
                                                                                                   handle_unknown='use_encoded_val...
                                feature_types=None, gamma=None, grow_policy=None,
                                importance_type=None,
                                interaction_constraints=None, learning_rate=None,
                                max_bin=None, max_cat_threshold=None,
                                max_cat_to_onehot=None, max_delta_step=None,
                                max_depth=None, max_leaves=None,
                                min_child_weight=None, missing=nan,
                                monotone_constraints=None, multi_strategy=None,
                                n_estimators=None, n_jobs=None,
                                num_parallel_tree=None, random_state=42, ...))]),
 'LightGBM': Pipeline(steps=[('preprocessor',
                  ColumnTransformer(remainder='passthrough',
                                    transformers=[('ohe',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse=False),
                                                   ['Gender',
                                                    'Transportation_used']),
                                                  ('oe',
                                                   ColumnTransformer(remainder='passthrough',
                                                                     transformers=[('food',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently',
                                                                                                                'Always']],
                                                                                                   handle_unknown='use_encoded_val...
                                                                                                   unknown_value=-1),
                                                                                    ['Consump_of_food_btw_meals']),
                                                                                   ('alcohol',
                                                                                    OrdinalEncoder(categories=[['0',
                                                                                                                'Sometimes',
                                                                                                                'Frequently']],
                                                                                                   handle_unknown='use_encoded_value',
                                                                                                   unknown_value=-1),
                                                                                    ['Alcohol_consumption'])]),
                                                   ['Consump_of_food_btw_meals',
                                                    'Alcohol_consumption']),
                                                  ('scale', StandardScaler(),
                                                   ['Age', 'Height',
                                                    'Weight'])])),
                 ('classifier', LGBMClassifier(random_state=42))]),
 'Gradient Boosting': Pipeline(steps=[('preprocessor',
                  ColumnTransformer(remainder='passthrough',
                                    transformers=[('ohe',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse=False),
                                                   ['Gender',
                                                    'Transportation_used']),
                                                  ('oe',
                                                   ColumnTransformer(remainder='passthrough',
                                                                     transformers=[('food',

In [71]:
# pipe.fit(X_train,y_train)

results = {}
for model_name, pipeline in pipelines.items():
    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')
    f1 = f1_score(y_test, y_pred, average='macro')
    results[model_name] = {
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1 Score': f1
    }

C:\Users\User\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\User\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\User\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\User\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\User\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\User\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\User\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000872 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1831
[LightGBM] [Info] Number of data points in the train set: 16606, number of used features: 20
[LightGBM] [Info] Start training from score -2.117117
[LightGBM] [Info] Start training from score -1.911230
[LightGBM] [Info] Start training from score -1.948141
[LightGBM] [Info] Start training from score -1.857720
[LightGBM] [Info] Start training from score -1.633574
[LightGBM] [Info] Start training from score -2.145531
[LightGBM] [Info] Start training from score -2.112625

C:\Users\User\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [72]:
# y_pred = pipe.predict(X_test)

# Display the results
results_df = pd.DataFrame(results).T
print(results_df)

                        Accuracy  Precision    Recall  F1 Score
Decision Tree           0.841522   0.825673  0.825544  0.825445
Random Forest           0.890896   0.880419  0.878443  0.879273
Support Vector Machine  0.877408   0.863922  0.864982  0.864290
Ada Boost               0.693642   0.673051  0.657889  0.653782
Neural Network          0.873073   0.861975  0.858836  0.858468
XGBoost                 0.902457   0.892928  0.891892  0.892327
LightGBM                0.901252   0.891069  0.890367  0.890691
Gradient Boosting       0.904624   0.894393  0.894013  0.894187

In [73]:
# xyz = pipelines['Gradient Boosting']
import pickle

In [74]:
# Identify the best model based on accuracy
best_model_name = results_df['Accuracy'].idxmax()

In [75]:
best_pipeline = pipelines[best_model_name]

In [76]:
# Save the best pipeline using pickle
with open('best_model_pipeline.pkl', 'wb') as file:
    pickle.dump(best_pipeline, file)

In [43]:
print(f"Best model ({best_model_name}) saved successfully.")

Best model (Gradient Boosting) saved successfully.

In [47]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [49]:
X_test_transformed

array([[1.000000e+00, 0.000000e+00, 0.000000e+00, ..., 1.292479e+00,
        6.526400e-02, 7.113310e-01],
       [0.000000e+00, 1.000000e+00, 0.000000e+00, ..., 2.000000e+00,
        1.000000e+00, 1.000000e+00],
       [1.000000e+00, 0.000000e+00, 0.000000e+00, ..., 2.847264e+00,
        2.000000e+00, 2.600000e-03],
       ...,
       [1.000000e+00, 0.000000e+00, 0.000000e+00, ..., 1.998108e+00,
        0.000000e+00, 1.382906e+00],
       [0.000000e+00, 1.000000e+00, 1.000000e+00, ..., 2.175632e+00,
        2.000000e+00, 0.000000e+00],
       [0.000000e+00, 1.000000e+00, 0.000000e+00, ..., 2.000000e+00,
        1.000000e+00, 0.000000e+00]])

In [50]:
# Convert the transformed data to a DataFrame
transformed_feature_names = (
    preprocessor.named_transformers_['ohe'].get_feature_names_out(categorical_cols).tolist() +
    ordinal_cols + 
    numerical_cols
)

In [51]:
transformed_feature_names

['Gender_Female',
 'Gender_Male',
 'Transportation_used_Automobile',
 'Transportation_used_Bike',
 'Transportation_used_Motorbike',
 'Transportation_used_Public_Transportation',
 'Transportation_used_Walking',
 'Consump_of_food_btw_meals',
 'Alcohol_consumption',
 'Age',
 'Height',
 'Weight']

In [57]:
X_train_transformed = pd.DataFrame(X_train_transformed,columns=preprocessor.get_feature_names_out(input_features=X_train.columns))

# Display the transformed data
(X_train_transformed.head())

,ohe__Gender_Female,ohe__Gender_Male,ohe__Transportation_used_Automobile,ohe__Transportation_used_Bike,ohe__Transportation_used_Motorbike,ohe__Transportation_used_Public_Transportation,ohe__Transportation_used_Walking,oe__food__Consump_of_food_btw_meals,oe__alcohol__Alcohol_consumption,scale__Age,scale__Height,scale__Weight,remainder__family_history_with_overweight,remainder__Freq_consump_of_high-caloric_food,remainder__Freq_of_veg_consump,remainder__No._of_main_meals,remainder__SMOKE,remainder__Daily_water_intake(L),remainder__Phy_activity_freq,remainder__Time_using_tech_devices
0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,-1.162898,0.800816,0.343527,1.0,1.0,3.0,3.000000,0.0,2.000000,3.000000,1.0
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,-0.284123,0.610243,-1.256602,1.0,1.0,2.0,4.000000,0.0,2.000000,2.000000,1.0
2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,-0.459878,1.372928,1.294154,1.0,1.0,3.0,2.880817,0.0,1.645338,0.739881,0.0
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,3.055223,-1.379006,-0.302254,1.0,1.0,2.0,3.000000,0.0,1.000000,0.000000,0.0
4,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,-0.108368,1.144999,0.267553,1.0,0.0,3.0,3.000000,0.0,3.000000,2.000000,1.0